name: My FastAPI CI/CD App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: My test app deployed on Render
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render deployment
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"