name: My FastAPI CI/CD App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: My test app deployed on Render
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render deployment
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

  test:
    name: Run Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-phython@v5
        with:
          python-version: '3.10'
      

    
